# Generated by Django 5.2.17 on 2026-10-01 08:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clothingitem_category_alter_clothingitem_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Model confidence for the predicted class (0-1).', null=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('top', 'Topwear'), ('bottom', 'Bottomwear'), ('dress', 'Dress'), ('shoes', 'Footwear'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_path),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
